[package]
name = "birli"
description = "Common preprocessing tasks for the Murchison Widefield Array Epoch of Reionization pipeline"
version = "0.1.9"
readme = "README.md"
homepage = "https://github.com/MWATelescope/Birli"
repository = "https://github.com/MWATelescope/Birli"
authors = [
    "Derwent McElhinney <derwent.mcelhinney@curtin.edu.au>",
    "Christopher H. Jordan <christopherjordan87@gmail.com>",
]
edition = "2018"
license = "MPL-2.0"
keywords = ["radioastronomy", "mwa", "astronomy", "aoflagger", "cotter"]
categories = ["science", "parsing"]
exclude = ["tests/*", ".vscode/*", ".github/*", ".talismanrc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["aoflagger"]
aoflagger = ["aoflagger_sys"]

[dependencies]
clap = "2.33"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
cfg-if = "1.0.0"
env_logger = "0.9"
float-cmp = "0.9"
indicatif = { version = "0.16", features = ["rayon"] }
itertools = "0.10"
libc = "0.2"
log = "0.4"
mwa_rust_core = ">=0.1.1"
ndarray = { version = ">=0.14,<0.16", features = ["rayon"] }
rayon = "1.5"
regex = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
aoflagger_sys = { version= "0.1.*", optional = true }

[dev-dependencies]
assert_cli = "0.6"
criterion = "0.3"
glob = "0.3"
rustfmt = "0.10"
tempfile = "3.2"
csv = "1.1"
lexical = "5.2"

# ndarray 0.14.* depends on approx 0.4.0, which in turn uses num-complex 0.3.0.
# Forcing the versions here means that ndarrays of complex numbers can be
# tested!
approx = { version = "0.4.0", features = ["num-complex"] }
ndarray = { version = "0.14.*", features = ["approx"] }
num-complex = "0.3.0"

[[bench]]
name = "bench"
path = "benches"
harness = false

[profile.bench]
opt-level = 3
