[package]
name = "birli"
description = "Common preprocessing tasks for the Murchison Widefield Array Epoch of Reionization pipeline"
version = "0.1.3"
readme = "README.md"
homepage = "https://github.com/MWATelescope/Birli"
repository = "https://github.com/MWATelescope/Birli"
authors = ["Derwent McElhinney <derwent.mcelhinney@curtin.edu.au>"]
edition = "2018"
license = "MPL-2.0"
keywords = ["radioastronomy", "mwa", "astronomy", "aoflagger", "cotter"]
categories = ["science", "parsing"]
exclude = ["tests/*", ".vscode/*", ".github/*", ".talismanrc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
crossbeam-channel = "0.5.*"
crossbeam-utils = "0.8.*"
cxx = "1.0.32"
env_logger = "0.8.3"
erfa-sys = "0.1.*"
fitsio = "0.17.*"
fitsio-sys = "^0" # fitsio also uses fitsio-sys so ensure we both use the same
float-cmp = "0.8.*"
hifitime = "2.2.*"
indicatif = { version = "0.16.*", features = ["rayon"] }
itertools = "0.10.0"
libc = "0.2.86"
log = "0.4"
mwalib = "0.8.4"
ndarray = { version = "0.15.*", features = ["rayon"] }
num = "0.4.*"
rayon = "1.5.*"
regex = "1.4.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.*"

[dev-dependencies]
approx = { version = "0.5.*", features = ["num-complex"] }
assert_cli = "0.6.1"
criterion = "0.3"
glob = "0.3.0"
rustfmt = "0.10.0"
tempfile = "3.2.0"

[build-dependencies]
bindgen = "0.58.1"
cc = {version = "1.0.67", features = ["parallel"]}
cxx-build = "1.0.32"

[[bench]]
name = "bench"
harness = false

[profile.bench]
opt-level = 3
