[package]
authors = ["Derwent McElhinney <derwent.mcelhinney@curtin.edu.au>"]
description = "Common preprocessing tasks for the Murchison Widefield Array Epoch of Reionization pipeline"
edition = "2018"
name = "birli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
mwalib = "0.6.2"
cxx = "1.0.32"
libc = "0.2.86"
thiserror = "1.0.*"
fitsio = "0.17.*"
regex = "1.4.*"
rayon = ">=1.3,<1.6"

[dev-dependencies]
assert_cli = "0.6.1"
rustfmt = "0.10.0"
tempdir = "0.3.7"
glob = "0.3.0"

[build-dependencies]
bindgen = "0.57.0"
cxx-build = "1.0.32"
cc = {version = "1.0.67", features = ["parallel"]}
