[package]
name = "birli"
description = "Common preprocessing tasks for the Murchison Widefield Array Epoch of Reionization pipeline"
version = "0.1.0"
readme = "README.md"
homepage = "https://github.com/MWATelescope/Birli"
repository = "https://github.com/MWATelescope/Birli"
authors = ["Derwent McElhinney <derwent.mcelhinney@curtin.edu.au>"]
edition = "2018"
license = "MPL-2.0"
keywords = ["radioastronomy", "mwa", "astronomy", "aoflagger", "cotter"]
categories = ["science","parsing"]
exclude = ["tests/*", ".vscode/*",".github/*", ".talismanrc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
cxx = "1.0.32"
fitsio = "0.17.*"
fitsio-sys = "^0" # fitsio also uses fitsio-sys so ensure we both use the same
libc = "0.2.86"
mwalib = "0.6.2"
rayon = ">=1.3,<1.6"
regex = "1.4.*"
thiserror = "1.0.*"

[dev-dependencies]
assert_cli = "0.6.1"
rustfmt = "0.10.0"
glob = "0.3.0"
tempfile = "3.2.0"

[build-dependencies]
bindgen = "0.57.0"
cc = {version = "1.0.67", features = ["parallel"]}
cxx-build = "1.0.32"
