# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push]

name: Benchmarks

jobs:
  test:
    name: Benchmarks
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo Bench
        run: |
          cargo update -p cxx --precise 1.0.54 || echo "cargo update cxx failed"
          cargo update -p cxx-build --precise 1.0.54 || echo "cargo update cxx-build failed"
          cargo update -p proc-macro2 --precise 1.0.28 || echo "cargo update proc-macro2 failed"
          cargo update -p approx:0.5.0 --precise 0.4.0 || echo "cargo update approx failed"
          cargo update -p ndarray:0.15.3 --precise 0.14.0 || echo "cargo update ndarray failed"
          cargo bench
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
          BIRLI_TEST_DIR: /mnt/data

      - name: install zip
        run: |
          sudo apt-get update \
          && sudo apt-get install -y zip

      - name: Zip benchmark results
        run: zip -r criterion.zip target/criterion/*

      - uses: actions/upload-artifact@v2
        with:
          name: criterion.zip
          path: criterion.zip
