on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  pull_request:

name: clippy

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: mwatelescope/birli:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Run cargo check, fmt, clippy
        run: |
          cargo check --all
          cargo fmt --all -- --check
          cargo clippy --all -- -D warnings
