# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

# Do this on every push, but don't double up on tags
on:
  push:
    tags-ignore:
      - '**'
    pull_request:
    branches:
    - '**'

name: Generate Coverage report

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: mwatelescope/marlu:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: nightly-2022-01-14
          component: llvm-tools-preview

      - name: install cargo-llvm-cov
        run: cargo +nightly-2022-01-14 install cargo-llvm-cov

      - name: Generate test lcov coverage into coverage/ dir
        run: |
          export PATH="${HOME}/.cargo/bin:${PATH}"
          mkdir -p coverage
          cargo +nightly-2022-01-14 llvm-cov --all --lcov --output-path coverage/coverage.lcov
          # this uses the result of the previous run to generate a text summary
          cargo +nightly-2022-01-14 llvm-cov --no-run

      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
