# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

# Do this on every push, but don't double up on tags
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  pull_request:

name: Generate Coverage report

jobs:
  coverage:
    runs-on: ubuntu-latest
    container: mwatelescope/birli:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate test lcov coverage into coverage/ dir
        run: |
          cargo install --force cargo-llvm-cov
          mkdir -p coverage
          /opt/cargo/bin/cargo llvm-cov --all --locked --lcov --output-path coverage/coverage.lcov
          # this uses the result of the previous run to generate a text summary
          /opt/cargo/bin/cargo llvm-cov --no-run --locked

      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
