# this tests that the latest docker image works, and does linter checks
# linter checks happen here because docker images are faster than waiting for
# dependencies to install on GitHub Actions VMs
on: [push, pull_request]

name: Docker Tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mwatelescope/birli:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          buildArgs: TEST_SHIM="cargo test --no-default-features; cargo test; cargo clean; rm -rf target"