on: [push, pull_request]

name: Docker Tests

jobs:
  test:
    name: Docker Tests
    runs-on: ubuntu-latest
    container: mwatelescope/birli:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Stable toolchain
        run: |
          rustup set profile default
          rustup toolchain install stable --component rustfmt,clippy
          rustup default stable

      - name: Cargo Make CI
        run: cargo make ci
