on: [push, pull_request]

name: Docker Tests

jobs:
  check:
    name: Docker Checks
    runs-on: ubuntu-latest
    container: mwatelescope/birli:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: /opt/cargo/bin/cargo check
      - run: /opt/cargo/bin/cargo fmt --all -- --check
      - run: /opt/cargo/bin/cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Docker Tests
    runs-on: ubuntu-latest
    container: mwatelescope/birli:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: /opt/cargo/bin/cargo test --release

  test_no_default:
    name: Docker Tests - No Default
    runs-on: ubuntu-latest
    container: mwatelescope/birli:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: /opt/cargo/bin/cargo test --no-default-features --release
