# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: 
  push:
    tags-ignore:
      - '**'
    pull_request:
    branches:
    - '**'

name: Linux Tests

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-18.04", "ubuntu-20.04"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install apt dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y \
            build-essential \
            casacore-data \
            casacore-dev \
            cmake \
            curl \
            git \
            libblas-dev \
            libboost-date-time-dev \
            libboost-filesystem-dev \
            libboost-system-dev \
            libboost-test-dev \
            libfftw3-dev \
            libgsl-dev \
            libgtkmm-3.0-dev \
            liblapack-dev \
            liblua5.3-dev \
            libpng-dev \
            libpython3-dev \
            libssl-dev \
            libxml2-dev \
            pkg-config \
            python3 \
            unzip \
            wget \
            zip

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Install Dependencies
        run: cargo make install_deps

      - name: Cargo Make CI
        run: cargo make ci
        env:
          LD_LIBRARY_PATH: /usr/local/lib/:/usr/lib/x86_64-linux-gnu/

  test_no_default:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install apt dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y \
            build-essential \
            cmake \
            curl \
            git \
            unzip \
            wget \
            zip

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Install Dependencies
        run: |
          cargo make linux_install_cfitsio
          cargo make linux_install_erfa

      - name: Cargo Test
        run: |
          cargo make update
          cargo test --no-default-features
        env:
          LD_LIBRARY_PATH: /usr/local/lib/:/usr/lib/x86_64-linux-gnu/
