# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push, pull_request]

name: Linux Tests

jobs:
  test:
    name: Linux Tests
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Install AOFlagger Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive \
          && sudo apt-get update \
          && sudo apt-get install -y \
            build-essential \
            casacore-data \
            casacore-dev \
            cmake \
            git  \
            libblas-dev \
            libboost-date-time-dev \
            libboost-filesystem-dev \
            libboost-system-dev \
            libboost-test-dev \
            libfftw3-dev \
            libgsl-dev \
            libgtkmm-3.0-dev \
            liblapack-dev \
            liblua5.3-dev \
            libpng-dev \
            libpython3-dev \
            libssl-dev \
            libxml2-dev \
            pkg-config \
            python3 \
            unzip

      - name: install cfitsio
        run: |
          cd /tmp \
          && wget http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz \
          && tar -zxvf cfitsio-3.49.tar.gz \
          && cd cfitsio-3.49/ \
          && CFLAGS="-O3" ./configure --prefix=/usr/local --enable-reentrant --enable-ssse3 --enable-sse2 \
          && make -j \
          && sudo make install

      # && sudo wget https://gitlab.com/aroffringa/aoflagger/-/archive/v3.0.0/aoflagger-v3.0.0.tar.gz \
      # && sudo tar -zxvf aoflagger-v3.0.0.tar.gz \
      # && cd aoflagger-v3.0.0 \
      - name: Install AOFlagger
        run: |
          cd /tmp \
          && git clone --recurse-submodules https://gitlab.com/aroffringa/aoflagger.git \
          && cd aoflagger \
          && chmod a+rwx . \
          && mkdir build \
          && cd build \
          && cmake .. \
          && make \
          && sudo make install \

      - name: Install Birli Dependencies
        run: |
          cargo make install_deps

      - name: Cargo Make CI
        run: cargo make ci
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
