# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  push:
    tags-ignore:
      - '**'
    pull_request:
    branches:
    - '**'

name: Linux Tests

jobs:
  test:
    strategy:
      matrix:
        os:
          # - "ubuntu-18.04", <- broken 2022-03-02
          - "ubuntu-20.04"
          # - "ubuntu-22.04"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install apt dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y \
            build-essential \
            cmake \
            curl \
            git \
            unzip \
            wget \
            zip

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Install Dependencies
        run: cargo make install_deps

      - name: Cargo Test
        run: cargo test
        env:
          LD_LIBRARY_PATH: /usr/local/lib/:/usr/lib/x86_64-linux-gnu/

  test_no_default:
    name: "Linux tests without aoflagger"
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install apt dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y \
            build-essential \
            cmake \
            curl \
            git \
            unzip \
            wget \
            zip

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Install Dependencies
        run: |
          cargo make linux_install_cfitsio
          cargo make linux_install_erfa

      - name: Cargo Test No Default
        run: |
          cargo test --no-default-features
        env:
          LD_LIBRARY_PATH: /usr/local/lib/:/usr/lib/x86_64-linux-gnu/
