# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  push:
    tags-ignore:
      - '**'
    branches:
    - '**'
  pull_request:

name: Linux Tests

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-18.04"
          - "ubuntu-20.04"
          - "ubuntu-22.04"
        feature_set:
          - "_no_flag"
          - ""
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Install deps
        uses: actions-rs/cargo@v1
        with:
          command: make
          # if aoflagger not enabled, you only need cfitsio
          args: install_deps${{ matrix.feature_set }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: test${{ matrix.feature_set }}
        env:
          LD_LIBRARY_PATH: /usr/local/lib/:/usr/lib/x86_64-linux-gnu/