# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: MacOS Tests
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request: null
jobs:
  test:
    name: MacOS Tests
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
    continue-on-error: true
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: 'rustfmt, clippy'
      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1
      - name: Install Dependencies
        run: |
          # cargo make install_deps # doesn't work
          brew install casacore/tap/casacore mwatelescope/tap/aoflagger
      - name: Run tests
        run: |
          cargo make test_no_default
          cargo make test_no_flag
          cargo make test
        env:
          DYLD_FALLBACK_LIBRARY_PATH: /opt/homebrew/lib/
          AOFLAGGER_LIB: /opt/homebrew/lib/
          AOFLAGGER_INCLUDE_DIR: /opt/homebrew/include/
