# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: MacOS Tests
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request: null
jobs:
  test:
    name: MacOS Tests
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
    continue-on-error: true
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: 'rustfmt, clippy'
      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1
      - name: Install Dependencies
        run: |
          # cargo make install_deps
          # doesn't work on macos, brew install ... says you need arch -arm64 brew ...
          # but there's no way to distinguish between macos-13 and macos-14
          # using uname -m or arch
          # https://github.com/actions/runner-images/issues/9471#issuecomment-1992603303
          for f in $(find /usr/local/bin -type l -print); do \
            (readlink $f | grep -q -s "/Library") && echo Removing "$f" && rm -f "$f"; \
          done
          INSTALL="brew install"
          [ "${{ matrix.os }}" == "macos-14" ] && INSTALL="arch -arm64 brew install"
          $INSTALL mwatelescope/tap/aoflagger
          echo "DYLD_FALLBACK_LIBRARY_PATH=$(brew --prefix)/lib/" >> $GITHUB_ENV
          echo "AOFLAGGER_LIB=$(brew --prefix)/lib/" >> $GITHUB_ENV
          echo "AOFLAGGER_INCLUDE_DIR=$(brew --prefix)/include/" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig/" >> $GITHUB_ENV
      - name: Run tests
        run: |
          cargo make test_no_default
          cargo make test_no_flag
          cargo make test
